spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url:
    driver-class-name:
    username: root
    password: '1111'
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true

    properties:
      format-sql: true
      hibernate:
        show-sql: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  mustache:
    suffix: .html

logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type: trace